name: Order Management
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Publish to SwaggerHub
        run: |
          npm i -g swaggerhub-cli
          export SWAGGERHUB_API_KEY=${{ secrets.SWAGGERHUB_API_KEY }}
          swaggerhub api:get MATHIEUKAMVITY/order-management-api -j > published-swagger.json
          npm install -g json-diff
          json-diff published-swagger.json swagger.json